// Generated by tools/build_sheet.py - do not edit by hand.
// Page coordinates in mm, origin at the top-left of the A4 sheet, y downwards.
export const G = {
  "pageW": 210.0,
  "pageH": 297.0,
  "targetH": 263.0,
  "xA": 40.0,
  "xB": 170.0,
  "beamY": 122.0,
  "beamHalf": 1.5,
  "loadTipY": 120.5,
  "loadTailY": 101.0,
  "dimChainY": 152.0,
  "dimSpanY": 160.0,
  "reactTipY": 134.5,
  "reactTailY": 149.0,
  "udlTopY": 109.0,
  "sfdBase": 184.0,
  "sfdScale": 0.45,
  "bmdBase": 212.0,
  "bmdScale": 0.9,
  "deflScale": 8.0,
  "overlay": {
    "y0": 92.0,
    "y1": 252.0,
    "pxPerMM": 6
  },
  "view2d": {
    "x0": 12.0,
    "x1": 198.0,
    "y0": 92.0,
    "y1": 252.0
  },
  "problem": {
    "L": 4.0,
    "P": 20.0,
    "a0": 1.5,
    "step": 0.1,
    "aMin": 0.1,
    "aMax": 3.9,
    "w": 10.0,
    "s0": 2.0,
    "e0": 4.0,
    "minLen": 0.5
  },
  "targetPxPerMM": 5,
  "mmPerM": 32.5,
  "printedLoadX": 88.75,
  "printedUdlX": [
    105.0,
    170.0
  ],
  "targetPx": {
    "w": 1050,
    "h": 1315
  }
};
